baseurl = "https://nicksloan.org/"
title = "Nick Sloan"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"
relativeURLs = true
canonifyURLs = false

[author]
name = "Nick Sloan"

[params]
colorscheme = "white"
tagline = ""
footer = "&copy; 2016 Nick Sloan"
description = "A blog about programming by Nick Sloan."
keywords = ""
github = "https://github.com/nicksloan"
bitbucket = "https://bitbucket.org/nicksloan"
twitter = "https://twitter.com/nicksloan"
facebook = "https://facebook.com/nasloan"

[menu]

[[menu.main]]
identifier = "home"
name       = "home"
url        = "/"
weight     = 0
